# Generated by Django 5.2.7 on 2025-11-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
